# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/pi/Documents/PythonProject/EricWall 4/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 320)
        self.MainTab = QtWidgets.QTabWidget(Dialog)
        self.MainTab.setGeometry(QtCore.QRect(60, 0, 461, 320))
        self.MainTab.setTabPosition(QtWidgets.QTabWidget.East)
        self.MainTab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.MainTab.setIconSize(QtCore.QSize(20, 20))
        self.MainTab.setObjectName("MainTab")
        self.Tab_Home = QtWidgets.QWidget()
        self.Tab_Home.setObjectName("Tab_Home")
        self.TimeLabel = QtWidgets.QLabel(self.Tab_Home)
        self.TimeLabel.setGeometry(QtCore.QRect(10, 130, 241, 111))
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(50)
        self.TimeLabel.setFont(font)
        self.TimeLabel.setText("")
        self.TimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TimeLabel.setObjectName("TimeLabel")
        self.WN_Location = QtWidgets.QLabel(self.Tab_Home)
        self.WN_Location.setGeometry(QtCore.QRect(300, 100, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setKerning(False)
        self.WN_Location.setFont(font)
        self.WN_Location.setText("")
        self.WN_Location.setAlignment(QtCore.Qt.AlignCenter)
        self.WN_Location.setObjectName("WN_Location")
        self.pushButton_2 = QtWidgets.QPushButton(self.Tab_Home)
        self.pushButton_2.setGeometry(QtCore.QRect(347, 260, 45, 45))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Button_Index/V4Beta3_BgShutDownBtn_45x45.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.Tab_Home)
        self.pushButton.setGeometry(QtCore.QRect(293, 260, 45, 45))
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Button_Index/V4Beta3_BgRefreshDownBtn_45x45.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(100, 100))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.Tab_Home)
        self.label.setGeometry(QtCore.QRect(0, 0, 420, 320))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setPixmap(QtGui.QPixmap(":/Bg/HomeBg"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.DateLabel = QtWidgets.QLabel(self.Tab_Home)
        self.DateLabel.setGeometry(QtCore.QRect(40, 100, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.DateLabel.setFont(font)
        self.DateLabel.setText("")
        self.DateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.DateLabel.setObjectName("DateLabel")
        self.SecondLabel = QtWidgets.QLabel(self.Tab_Home)
        self.SecondLabel.setGeometry(QtCore.QRect(240, 190, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.SecondLabel.setFont(font)
        self.SecondLabel.setText("")
        self.SecondLabel.setObjectName("SecondLabel")
        self.WN_Temp = QtWidgets.QLabel(self.Tab_Home)
        self.WN_Temp.setGeometry(QtCore.QRect(290, 130, 111, 61))
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(32)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.WN_Temp.setFont(font)
        self.WN_Temp.setText("")
        self.WN_Temp.setAlignment(QtCore.Qt.AlignCenter)
        self.WN_Temp.setObjectName("WN_Temp")
        self.WN_Status = QtWidgets.QLabel(self.Tab_Home)
        self.WN_Status.setGeometry(QtCore.QRect(290, 180, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.WN_Status.setFont(font)
        self.WN_Status.setText("")
        self.WN_Status.setAlignment(QtCore.Qt.AlignCenter)
        self.WN_Status.setObjectName("WN_Status")
        self.label.raise_()
        self.TimeLabel.raise_()
        self.pushButton_2.raise_()
        self.pushButton.raise_()
        self.DateLabel.raise_()
        self.SecondLabel.raise_()
        self.WN_Temp.raise_()
        self.WN_Status.raise_()
        self.WN_Location.raise_()
        self.MainTab.addTab(self.Tab_Home, "")
        self.Tab_Weather = QtWidgets.QWidget()
        self.Tab_Weather.setObjectName("Tab_Weather")
        self.ForecastToday = QtWidgets.QLabel(self.Tab_Weather)
        self.ForecastToday.setGeometry(QtCore.QRect(300, 80, 91, 101))
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(13)
        self.ForecastToday.setFont(font)
        self.ForecastToday.setText("")
        self.ForecastToday.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ForecastToday.setObjectName("ForecastToday")
        self.ForecastNx_Temp = QtWidgets.QLabel(self.Tab_Weather)
        self.ForecastNx_Temp.setGeometry(QtCore.QRect(276, 226, 91, 35))
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(14)
        self.ForecastNx_Temp.setFont(font)
        self.ForecastNx_Temp.setText("")
        self.ForecastNx_Temp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ForecastNx_Temp.setObjectName("ForecastNx_Temp")
        self.Bg_Weather = QtWidgets.QLabel(self.Tab_Weather)
        self.Bg_Weather.setGeometry(QtCore.QRect(0, 0, 420, 320))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bg_Weather.sizePolicy().hasHeightForWidth())
        self.Bg_Weather.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Bg_Weather.setFont(font)
        self.Bg_Weather.setText("")
        self.Bg_Weather.setTextFormat(QtCore.Qt.RichText)
        self.Bg_Weather.setPixmap(QtGui.QPixmap(":/Bg/WeatherBg"))
        self.Bg_Weather.setScaledContents(True)
        self.Bg_Weather.setAlignment(QtCore.Qt.AlignCenter)
        self.Bg_Weather.setWordWrap(False)
        self.Bg_Weather.setObjectName("Bg_Weather")
        self.WF_Location = QtWidgets.QLabel(self.Tab_Weather)
        self.WF_Location.setGeometry(QtCore.QRect(34, 68, 151, 31))
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(12)
        self.WF_Location.setFont(font)
        self.WF_Location.setText("")
        self.WF_Location.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.WF_Location.setObjectName("WF_Location")
        self.WF_Date = QtWidgets.QLabel(self.Tab_Weather)
        self.WF_Date.setGeometry(QtCore.QRect(34, 96, 151, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.WF_Date.setFont(font)
        self.WF_Date.setText("")
        self.WF_Date.setObjectName("WF_Date")
        self.WF_Temp = QtWidgets.QLabel(self.Tab_Weather)
        self.WF_Temp.setGeometry(QtCore.QRect(34, 192, 111, 61))
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(37)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.WF_Temp.setFont(font)
        self.WF_Temp.setText("")
        self.WF_Temp.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.WF_Temp.setObjectName("WF_Temp")
        self.WF_Status = QtWidgets.QLabel(self.Tab_Weather)
        self.WF_Status.setGeometry(QtCore.QRect(34, 251, 151, 31))
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(13)
        self.WF_Status.setFont(font)
        self.WF_Status.setText("")
        self.WF_Status.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.WF_Status.setObjectName("WF_Status")
        self.WF_Title = QtWidgets.QLabel(self.Tab_Weather)
        self.WF_Title.setGeometry(QtCore.QRect(194, 76, 81, 31))
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(11)
        self.WF_Title.setFont(font)
        self.WF_Title.setText("")
        self.WF_Title.setObjectName("WF_Title")
        self.WF_Title_2 = QtWidgets.QLabel(self.Tab_Weather)
        self.WF_Title_2.setGeometry(QtCore.QRect(194, 102, 81, 31))
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(11)
        self.WF_Title_2.setFont(font)
        self.WF_Title_2.setText("")
        self.WF_Title_2.setObjectName("WF_Title_2")
        self.WF_Title_3 = QtWidgets.QLabel(self.Tab_Weather)
        self.WF_Title_3.setGeometry(QtCore.QRect(194, 128, 81, 31))
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(11)
        self.WF_Title_3.setFont(font)
        self.WF_Title_3.setText("")
        self.WF_Title_3.setObjectName("WF_Title_3")
        self.WF_Title_4 = QtWidgets.QLabel(self.Tab_Weather)
        self.WF_Title_4.setGeometry(QtCore.QRect(194, 154, 81, 31))
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(11)
        self.WF_Title_4.setFont(font)
        self.WF_Title_4.setText("")
        self.WF_Title_4.setObjectName("WF_Title_4")
        self.WF_Nx_Title = QtWidgets.QLabel(self.Tab_Weather)
        self.WF_Nx_Title.setGeometry(QtCore.QRect(213, 198, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.WF_Nx_Title.setFont(font)
        self.WF_Nx_Title.setText("")
        self.WF_Nx_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.WF_Nx_Title.setObjectName("WF_Nx_Title")
        self.WF_Nx_Time = QtWidgets.QLabel(self.Tab_Weather)
        self.WF_Nx_Time.setGeometry(QtCore.QRect(209, 226, 61, 41))
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(10)
        self.WF_Nx_Time.setFont(font)
        self.WF_Nx_Time.setText("")
        self.WF_Nx_Time.setAlignment(QtCore.Qt.AlignCenter)
        self.WF_Nx_Time.setObjectName("WF_Nx_Time")
        self.ForecastNx_Status = QtWidgets.QLabel(self.Tab_Weather)
        self.ForecastNx_Status.setGeometry(QtCore.QRect(276, 202, 91, 31))
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(10)
        self.ForecastNx_Status.setFont(font)
        self.ForecastNx_Status.setText("")
        self.ForecastNx_Status.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ForecastNx_Status.setObjectName("ForecastNx_Status")
        self.RefreshButton = QtWidgets.QPushButton(self.Tab_Weather)
        self.RefreshButton.setGeometry(QtCore.QRect(368, 9, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RefreshButton.sizePolicy().hasHeightForWidth())
        self.RefreshButton.setSizePolicy(sizePolicy)
        self.RefreshButton.setText("")
        self.RefreshButton.setIcon(icon1)
        self.RefreshButton.setIconSize(QtCore.QSize(80, 80))
        self.RefreshButton.setObjectName("RefreshButton")
        self.Bg_Weather.raise_()
        self.ForecastToday.raise_()
        self.WF_Location.raise_()
        self.WF_Date.raise_()
        self.WF_Temp.raise_()
        self.WF_Status.raise_()
        self.WF_Title.raise_()
        self.WF_Title_2.raise_()
        self.WF_Title_3.raise_()
        self.WF_Title_4.raise_()
        self.WF_Nx_Title.raise_()
        self.WF_Nx_Time.raise_()
        self.ForecastNx_Status.raise_()
        self.ForecastNx_Temp.raise_()
        self.RefreshButton.raise_()
        self.MainTab.addTab(self.Tab_Weather, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.Bg_About = QtWidgets.QLabel(self.tab)
        self.Bg_About.setGeometry(QtCore.QRect(0, 0, 420, 320))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bg_About.sizePolicy().hasHeightForWidth())
        self.Bg_About.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Bg_About.setFont(font)
        self.Bg_About.setText("")
        self.Bg_About.setTextFormat(QtCore.Qt.RichText)
        self.Bg_About.setPixmap(QtGui.QPixmap(":/Bg/AboutBg"))
        self.Bg_About.setScaledContents(True)
        self.Bg_About.setAlignment(QtCore.Qt.AlignCenter)
        self.Bg_About.setWordWrap(False)
        self.Bg_About.setObjectName("Bg_About")
        self.MainTab.addTab(self.tab, "")
        self.HomeBtn = QtWidgets.QPushButton(Dialog)
        self.HomeBtn.setGeometry(QtCore.QRect(0, 80, 61, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HomeBtn.sizePolicy().hasHeightForWidth())
        self.HomeBtn.setSizePolicy(sizePolicy)
        self.HomeBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.HomeBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Button_Left/V4Beta3_HomeBtn_60x60.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.HomeBtn.setIcon(icon2)
        self.HomeBtn.setIconSize(QtCore.QSize(120, 120))
        self.HomeBtn.setChecked(False)
        self.HomeBtn.setObjectName("HomeBtn")
        self.WeatherBtn = QtWidgets.QPushButton(Dialog)
        self.WeatherBtn.setGeometry(QtCore.QRect(0, 140, 61, 61))
        self.WeatherBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Button_Left/V4Beta3_WeatherBtn_60x60.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.WeatherBtn.setIcon(icon3)
        self.WeatherBtn.setIconSize(QtCore.QSize(120, 120))
        self.WeatherBtn.setObjectName("WeatherBtn")
        self.AboutBtn = QtWidgets.QPushButton(Dialog)
        self.AboutBtn.setGeometry(QtCore.QRect(0, 200, 61, 61))
        self.AboutBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Button_Left/V4Beta3_AboutBtn_60x60.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AboutBtn.setIcon(icon4)
        self.AboutBtn.setIconSize(QtCore.QSize(120, 120))
        self.AboutBtn.setObjectName("AboutBtn")
        self.LeftSlide = QtWidgets.QLabel(Dialog)
        self.LeftSlide.setGeometry(QtCore.QRect(0, 0, 63, 320))
        self.LeftSlide.setText("")
        self.LeftSlide.setPixmap(QtGui.QPixmap(":/Bg/Left_Slide.bmp"))
        self.LeftSlide.setScaledContents(True)
        self.LeftSlide.setObjectName("LeftSlide")
        self.LeftSlide.raise_()
        self.MainTab.raise_()
        self.HomeBtn.raise_()
        self.WeatherBtn.raise_()
        self.AboutBtn.raise_()

        self.retranslateUi(Dialog)
        self.MainTab.setCurrentIndex(0)
        self.pushButton.clicked.connect(Dialog.QueryWeather)
        self.pushButton_2.clicked.connect(Dialog.close)
        self.HomeBtn.clicked.connect(Dialog.TabToHome)
        self.WeatherBtn.clicked.connect(Dialog.TabToWeather)
        self.AboutBtn.clicked.connect(Dialog.TabToAbout)
        self.RefreshButton.clicked.connect(Dialog.QueryWeather)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.MainTab.setTabText(self.MainTab.indexOf(self.Tab_Home), _translate("Dialog", "主页"))
        self.MainTab.setTabText(self.MainTab.indexOf(self.Tab_Weather), _translate("Dialog", "天气"))
        self.MainTab.setTabText(self.MainTab.indexOf(self.tab), _translate("Dialog", "关于"))

import Pictures_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

